apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: prometheus-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${SUPPORT_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
 
---
 
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ${GRAFANA_DOMAIN_NAME}-crt
spec:
  secretName: ${GRAFANA_DOMAIN_NAME}-crt
  dnsNames:
  - ${GRAFANA_DOMAIN_NAME}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ${GRAFANA_DOMAIN_NAME}
  issuerRef:
    name: prometheus-issuer
    kind: Issuer