es_host: ${DOCKER_HOST_NAME_ELASTICSEARCH}
es_port: ${DOCKER_ELASTICSEARCH_PORT}

name: "${DOCKER_DJANGO_HOST_NAME}: Down Docker Services Alert"
index: filebeat-*

is_enabled: true

type: any

query_key: message

realert:
  days: 1

query_delay:
  minutes: 20

filter:
- query:
  - query_string:
      query: "process.name:down_docker_services"

alert_text_type: alert_text_only

include : ["message"]

alert_text: "${DOCKER_DJANGO_HOST_NAME}:\n
{0}
"

alert_text_args: ["message"]

alert:
  - "slack"
#   - "email"

slack_webhook_url: "${DOCKER_SLACK_WEBHOOK_URL}"
slack_emoji_override: ":gear:"
slack_username_override: "ElastAlert"
slack_channel_override: "#ops-notifications"
slack_msg_color: "warning"
slack_title: "Down Docker Services Alert"

#email:
#  - "${DOCKER_DJANGO_ADMIN_EMAIL}"