domain_name:
docker_image:
image_version:
namespace:
letsencryptenv:
powa:
pg_host_name: contrax-db
pg_db_name: contrax1
pg_user: contrax1
pg_password: contrax1
pg_port: 5432
celery_replicas: 15
celery_cpu_request: 3
celery_cpu_limit: 3
celery_target_cpu_usage: 25
celery_doc_load_replicas: 25
celery_doc_load_cpu_request: 3
celery_doc_load_cpu_limit: 3
celery_doc_load_target_cpu_usage: 25
uwsgi_cpu_request: 2
uwsgi_memory_request: 4Gi
uwsgi_cpu_limit: 4
uwsgi_memory_limit: 8Gi
rabbitmq_cpu_request: 1
rabbitmq_memory_request: 1Gi
postgres_memory_request: 1Gi
postgres_memory_limit: 8Gi
docker_elasticsearch_replicas: 1
docker_rabbitmq_replicas: 1
docker_pg_replicas: 1
docker_elasticsearch_port: 9200
docker_host_name_elasticsearch: contrax-elasticsearch
mlflow_aws_bucket: contraxmlflowartifacts
mlflow_s3_endpoint_url: http://contrax-minio:9000
docker_minio_image: minio/minio:RELEASE.2020-01-03T19-12-21Z
docker_webdav_image: bytemark/webdav:2.4
docker_mlflow_tracking_image: lexpredict/mlflow-tracking-server:1.6.0-1
docker_curator_image: lexpredict/es-curator-cron:5.8.1-1
docker_elasticsearch_image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.2
docker_kibana_image: lexpredict/lexpredict-kibana:7.5.0
docker_metricbeat_image: docker.elastic.co/beats/metricbeat-oss:7.5.2
docker_rabbitmq_image: rabbitmq:3-management
docker_pg_image: postgres:11.5
docker_nginx_image: nginx:1.16.1-alpine
docker_redis_image: redis:5-alpine
docker_filebeat_image: docker.elastic.co/beats/filebeat-oss:7.5.2
storage_class_name: rook-ceph-block
