#shared-configmaps

apiVersion: v1
data:
  uwsgi.ini: |-
    readconfig_uwsgi.ini

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: uwsgi-ini-configmap

---

apiVersion: v1
data:
  local_settings_celery.py: |-
    readconfig_local_settings_celery.py

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: local-settings-celery-py-configmap

---

apiVersion: v1
data:
  local_settings_websrv.py: |-
    readconfig_local_settings_websrv.py

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: local-settings-websrv-py-configmap

---
{{ if eq .Values.pg_host_name "contrax-db" }}
#contrax-db

apiVersion: v1
data:
  backup-cron.conf: |-
    readconfig_backup-cron.conf

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pg-backup-cron-722aba991ba1ea855e6736133174990a

---

apiVersion: v1
data:
  postgresql.conf: |-
    readconfig_postgresql.conf

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: postgresqlconf-configmap

---

apiVersion: v1
data:
  postgresql.conf: |-
    readconfig_postgresql.conf

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: postgresqlconf-powa-configmap

---

apiVersion: v1
data:
  postgres-init.sql: |
    readconfig_postgres_init.sql

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pg-init-sql-106a59094d5cd047cb07f39e68db563a

---

apiVersion: v1
data:
  db-backup.sh: |
    readconfig_db-backup.sh

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: db-backup-configmap

---

apiVersion: v1
data:
  pg_hba.conf: |
    readconfig_pg_hba.conf

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pg-hba-configmap

---
{{ end }}

#contrax-elasticsearch

apiVersion: v1
data:
  elasticsearch.yml: |-
    readconfig_elasticsearch.yml

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: elasticsearch-yaml-config

---

#contrax-elastalert

apiVersion: v1
data:
  config.yaml: |-
    readconfig_elastalert-config.yaml

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: elastalert-config-yaml-configmap

---

apiVersion: v1
data:
  elastalert.yaml: |-
    readconfig_elastalert-config.yaml

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: elastalert-server-yaml-configmap

---

apiVersion: v1
data:
  config.json: |-
    readconfig_elastalert-server-config.json

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: elastalert-server-config-json-configmap

---

apiVersion: v1
data:
  elastalert-smtp-auth.yaml: |-
    readconfig_elastalert-smtp-auth.yaml

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: elastalert-smtp-auth-yaml-configmap

---

#contrax-filebeat

apiVersion: v1
data:
  filebeat.yml: |-
    readconfig_filebeat.yml

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: filebeat-1b84ea4a4555e9c33f0ea04461533050

---

#contrax-kibana

apiVersion: v1
data:
  kibana.yml: |-
    readconfig_kibana.yml

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: contrax-kibana-conf-configmap

---

#contrax-metricbeat

apiVersion: v1
data:
  metricbeat.yml: |-
    readconfig_metricbeat.yml

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: metricbeat-99b4e27a4f53a7c722f3e17e204d86c2

---

#contrax-nginx

apiVersion: v1
data:
  nginx-customer.conf: |-
    readconfig_nginx-customer.conf

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-cust-295d861acdf477ca42d4d66a2a29680a

---

#contrax-jupyter

apiVersion: v1
data:
  jupyter_notebook_config.py: |-
    readconfig_jupyter_notebook_config.py

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: jupyter-notebook-config-py-configmap

---

#contrax-powa-web

apiVersion: v1
data:
  powa-web.conf: |-
    readconfig_powa-web.conf

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: powa-web-configmap

---

#contrax-celery

apiVersion: v1
data:
  local_settings_celery.py:
    readconfig_local_settings_celery.py
    
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: local-settings-celery-configmap
